global:
  resolve_timeout: 5m

route:
  receiver: 'default'

receivers:
  - name: 'default'
    # For now we'll just log alerts, later we can add email/Slack
    webhook_configs:
      - url: 'http://localhost:5001/'  # test webhook
