name: Terraform AWS Plan

on:
  push:
    paths:
      - 'terraform-aws/**'
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format, Init, Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./terraform-aws

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-aws

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform-aws
